spring.application.name=backend
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:bojunkadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# JWT Secret
jwt.secret=change_this_secret_change_this_secret_change_this_secret
jwt.expiration=28800000
